---
- hosts: all

  roles:
    - role: ansible-elasticsearch
      es_instance_name: "node1"
      become: true
    - role: howtohelp

  tasks:
    - apt_repository: repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present
      become: true

    - name: update apt-get
      apt: update_cache=yes
      become: true

    - name: install required apt-get packages
      apt: name={{ item }} state=present force=yes
      become: true
      with_items:
        - curl
        - wget
        - tmux
        - git
        - inotify-tools
        - python-software-properties
        - python
        - ntp
        - heroku-toolbelt
